#############################################################################
# Makefile for building: path
# Generated by qmake (1.07a) (Qt 3.3.8c) on: Tue Dec  4 21:59:23 2018
# Project:  path.pro
# Template: subdirs
# Command: $(QMAKE) -o Makefile path.pro
#############################################################################

MAKEFILE =	Makefile
QMAKE    =	qmake
DEL_FILE =    rm -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p
INSTALL_FILE= 
INSTALL_DIR = 
SUBTARGETS =	 \
		sub-_-path_gran-paths_u_pro \
		sub-_-path_tIRI-paths0_u_pro \
		sub-_-path_tIRI_GR-paths0_u_pro \
		sub-_-pk2-pk2_u_pro \
		sub-_-pk3-pk3_u_pro \
		sub-_-pk4-pk4_u_pro \
		sub-_-profil-profil_u_pro

first: all

all: Makefile $(SUBTARGETS)

./path_gran/$(MAKEFILE).paths_u: 
	@$(CHK_DIR_EXISTS) "./path_gran" || $(MKDIR) "./path_gran"
	cd ./path_gran && $(QMAKE) paths_u.pro -o $(MAKEFILE).paths_u
sub-_-path_gran-paths_u_pro: ./path_gran/$(MAKEFILE).paths_u FORCE
	cd ./path_gran && $(MAKE) -f $(MAKEFILE).paths_u

./path_tIRI/$(MAKEFILE).paths0_u: 
	@$(CHK_DIR_EXISTS) "./path_tIRI" || $(MKDIR) "./path_tIRI"
	cd ./path_tIRI && $(QMAKE) paths0_u.pro -o $(MAKEFILE).paths0_u
sub-_-path_tIRI-paths0_u_pro: ./path_tIRI/$(MAKEFILE).paths0_u FORCE
	cd ./path_tIRI && $(MAKE) -f $(MAKEFILE).paths0_u

./path_tIRI_GR/$(MAKEFILE).paths0_u: 
	@$(CHK_DIR_EXISTS) "./path_tIRI_GR" || $(MKDIR) "./path_tIRI_GR"
	cd ./path_tIRI_GR && $(QMAKE) paths0_u.pro -o $(MAKEFILE).paths0_u
sub-_-path_tIRI_GR-paths0_u_pro: ./path_tIRI_GR/$(MAKEFILE).paths0_u FORCE
	cd ./path_tIRI_GR && $(MAKE) -f $(MAKEFILE).paths0_u

./pk2/$(MAKEFILE).pk2_u: 
	@$(CHK_DIR_EXISTS) "./pk2" || $(MKDIR) "./pk2"
	cd ./pk2 && $(QMAKE) pk2_u.pro -o $(MAKEFILE).pk2_u
sub-_-pk2-pk2_u_pro: ./pk2/$(MAKEFILE).pk2_u FORCE
	cd ./pk2 && $(MAKE) -f $(MAKEFILE).pk2_u

./pk3/$(MAKEFILE).pk3_u: 
	@$(CHK_DIR_EXISTS) "./pk3" || $(MKDIR) "./pk3"
	cd ./pk3 && $(QMAKE) pk3_u.pro -o $(MAKEFILE).pk3_u
sub-_-pk3-pk3_u_pro: ./pk3/$(MAKEFILE).pk3_u FORCE
	cd ./pk3 && $(MAKE) -f $(MAKEFILE).pk3_u

./pk4/$(MAKEFILE).pk4_u: 
	@$(CHK_DIR_EXISTS) "./pk4" || $(MKDIR) "./pk4"
	cd ./pk4 && $(QMAKE) pk4_u.pro -o $(MAKEFILE).pk4_u
sub-_-pk4-pk4_u_pro: ./pk4/$(MAKEFILE).pk4_u FORCE
	cd ./pk4 && $(MAKE) -f $(MAKEFILE).pk4_u

./profil/$(MAKEFILE).profil_u: 
	@$(CHK_DIR_EXISTS) "./profil" || $(MKDIR) "./profil"
	cd ./profil && $(QMAKE) profil_u.pro -o $(MAKEFILE).profil_u
sub-_-profil-profil_u_pro: ./profil/$(MAKEFILE).profil_u FORCE
	cd ./profil && $(MAKE) -f $(MAKEFILE).profil_u

Makefile: path.pro  /usr/lib/qt3/mkspecs/default/qmake.conf 
	$(QMAKE) -o Makefile path.pro
qmake: qmake_all
	@$(QMAKE) -o Makefile path.pro

all: $(SUBTARGETS)
qmake_all: ./path_gran/$(MAKEFILE).paths_u ./path_tIRI/$(MAKEFILE).paths0_u ./path_tIRI_GR/$(MAKEFILE).paths0_u ./pk2/$(MAKEFILE).pk2_u ./pk3/$(MAKEFILE).pk3_u ./pk4/$(MAKEFILE).pk4_u ./profil/$(MAKEFILE).profil_u
	 ( [ -d ./path_gran ] && cd ./path_gran ; grep "^qmake_all:" $(MAKEFILE).paths_u && $(MAKE) -f $(MAKEFILE).paths_u qmake_all; ) || true
	 ( [ -d ./path_tIRI ] && cd ./path_tIRI ; grep "^qmake_all:" $(MAKEFILE).paths0_u && $(MAKE) -f $(MAKEFILE).paths0_u qmake_all; ) || true
	 ( [ -d ./path_tIRI_GR ] && cd ./path_tIRI_GR ; grep "^qmake_all:" $(MAKEFILE).paths0_u && $(MAKE) -f $(MAKEFILE).paths0_u qmake_all; ) || true
	 ( [ -d ./pk2 ] && cd ./pk2 ; grep "^qmake_all:" $(MAKEFILE).pk2_u && $(MAKE) -f $(MAKEFILE).pk2_u qmake_all; ) || true
	 ( [ -d ./pk3 ] && cd ./pk3 ; grep "^qmake_all:" $(MAKEFILE).pk3_u && $(MAKE) -f $(MAKEFILE).pk3_u qmake_all; ) || true
	 ( [ -d ./pk4 ] && cd ./pk4 ; grep "^qmake_all:" $(MAKEFILE).pk4_u && $(MAKE) -f $(MAKEFILE).pk4_u qmake_all; ) || true
	 ( [ -d ./profil ] && cd ./profil ; grep "^qmake_all:" $(MAKEFILE).profil_u && $(MAKE) -f $(MAKEFILE).profil_u qmake_all; ) || true
clean uicables mocables uiclean mocclean lexclean yaccclean : qmake_all FORCE
	 ( [ -d ./path_gran ] && cd ./path_gran ; $(MAKE) -f $(MAKEFILE).paths_u $@; ) || true
	 ( [ -d ./path_tIRI ] && cd ./path_tIRI ; $(MAKE) -f $(MAKEFILE).paths0_u $@; ) || true
	 ( [ -d ./path_tIRI_GR ] && cd ./path_tIRI_GR ; $(MAKE) -f $(MAKEFILE).paths0_u $@; ) || true
	 ( [ -d ./pk2 ] && cd ./pk2 ; $(MAKE) -f $(MAKEFILE).pk2_u $@; ) || true
	 ( [ -d ./pk3 ] && cd ./pk3 ; $(MAKE) -f $(MAKEFILE).pk3_u $@; ) || true
	 ( [ -d ./pk4 ] && cd ./pk4 ; $(MAKE) -f $(MAKEFILE).pk4_u $@; ) || true
	 ( [ -d ./profil ] && cd ./profil ; $(MAKE) -f $(MAKEFILE).profil_u $@; ) || true
uninstall_subdirs: qmake_all FORCE
	 ( [ -d ./path_gran ] && cd ./path_gran ; $(MAKE) -f $(MAKEFILE).paths_u uninstall; ) || true
	 ( [ -d ./path_tIRI ] && cd ./path_tIRI ; $(MAKE) -f $(MAKEFILE).paths0_u uninstall; ) || true
	 ( [ -d ./path_tIRI_GR ] && cd ./path_tIRI_GR ; $(MAKE) -f $(MAKEFILE).paths0_u uninstall; ) || true
	 ( [ -d ./pk2 ] && cd ./pk2 ; $(MAKE) -f $(MAKEFILE).pk2_u uninstall; ) || true
	 ( [ -d ./pk3 ] && cd ./pk3 ; $(MAKE) -f $(MAKEFILE).pk3_u uninstall; ) || true
	 ( [ -d ./pk4 ] && cd ./pk4 ; $(MAKE) -f $(MAKEFILE).pk4_u uninstall; ) || true
	 ( [ -d ./profil ] && cd ./profil ; $(MAKE) -f $(MAKEFILE).profil_u uninstall; ) || true
install_subdirs: qmake_all FORCE
	 ( [ -d ./path_gran ] && cd ./path_gran ; $(MAKE) -f $(MAKEFILE).paths_u install; ) || true
	 ( [ -d ./path_tIRI ] && cd ./path_tIRI ; $(MAKE) -f $(MAKEFILE).paths0_u install; ) || true
	 ( [ -d ./path_tIRI_GR ] && cd ./path_tIRI_GR ; $(MAKE) -f $(MAKEFILE).paths0_u install; ) || true
	 ( [ -d ./pk2 ] && cd ./pk2 ; $(MAKE) -f $(MAKEFILE).pk2_u install; ) || true
	 ( [ -d ./pk3 ] && cd ./pk3 ; $(MAKE) -f $(MAKEFILE).pk3_u install; ) || true
	 ( [ -d ./pk4 ] && cd ./pk4 ; $(MAKE) -f $(MAKEFILE).pk4_u install; ) || true
	 ( [ -d ./profil ] && cd ./profil ; $(MAKE) -f $(MAKEFILE).profil_u install; ) || true
distclean: qmake_all FORCE
	 ( [ -d ./path_gran ] && cd ./path_gran ; $(MAKE) -f $(MAKEFILE).paths_u $@; $(DEL_FILE) $(MAKEFILE).paths_u; ) || true
	 ( [ -d ./path_tIRI ] && cd ./path_tIRI ; $(MAKE) -f $(MAKEFILE).paths0_u $@; $(DEL_FILE) $(MAKEFILE).paths0_u; ) || true
	 ( [ -d ./path_tIRI_GR ] && cd ./path_tIRI_GR ; $(MAKE) -f $(MAKEFILE).paths0_u $@; $(DEL_FILE) $(MAKEFILE).paths0_u; ) || true
	 ( [ -d ./pk2 ] && cd ./pk2 ; $(MAKE) -f $(MAKEFILE).pk2_u $@; $(DEL_FILE) $(MAKEFILE).pk2_u; ) || true
	 ( [ -d ./pk3 ] && cd ./pk3 ; $(MAKE) -f $(MAKEFILE).pk3_u $@; $(DEL_FILE) $(MAKEFILE).pk3_u; ) || true
	 ( [ -d ./pk4 ] && cd ./pk4 ; $(MAKE) -f $(MAKEFILE).pk4_u $@; $(DEL_FILE) $(MAKEFILE).pk4_u; ) || true
	 ( [ -d ./profil ] && cd ./profil ; $(MAKE) -f $(MAKEFILE).profil_u $@; $(DEL_FILE) $(MAKEFILE).profil_u; ) || true

install:  install_subdirs

uninstall:  uninstall_subdirs

FORCE:

